name = "sync-sheet-worker"
main = "index.js"
compatibility_date = "2026-06-28"

[[durable_objects.bindings]]
name = "FARM_ROOM_DO"
class_name = "FarmRoomDurableObject"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["FarmRoomDurableObject"]  # 🌟 ĐÃ SỬA: Thêm chữ _sqlite vào đây là xong!
